// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyTHs_vgPBbRIhrstEWssAOJOZ1J4KAjE',
    appId: '1:762061270948:web:c519979bcb36e18b385b31',
    messagingSenderId: '762061270948',
    projectId: 'starter-5a5af',
    authDomain: 'starter-5a5af.firebaseapp.com',
    storageBucket: 'starter-5a5af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKu1HqqK_VYnJEBq57pohE_u-uROhCek8',
    appId: '1:762061270948:android:773beaa350a29e23385b31',
    messagingSenderId: '762061270948',
    projectId: 'starter-5a5af',
    storageBucket: 'starter-5a5af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBViMtpnHXhf210LJtSDnAwhsxcJAs4yuI',
    appId: '1:762061270948:ios:2cc600da9d463150385b31',
    messagingSenderId: '762061270948',
    projectId: 'starter-5a5af',
    storageBucket: 'starter-5a5af.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBViMtpnHXhf210LJtSDnAwhsxcJAs4yuI',
    appId: '1:762061270948:ios:2cc600da9d463150385b31',
    messagingSenderId: '762061270948',
    projectId: 'starter-5a5af',
    storageBucket: 'starter-5a5af.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyTHs_vgPBbRIhrstEWssAOJOZ1J4KAjE',
    appId: '1:762061270948:web:96e8656f3f9591a7385b31',
    messagingSenderId: '762061270948',
    projectId: 'starter-5a5af',
    authDomain: 'starter-5a5af.firebaseapp.com',
    storageBucket: 'starter-5a5af.firebasestorage.app',
  );
}
